In [4]:
pip install --upgrade --force-reinstall numpy scipy

Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/75/c9/9bec03675192077467a9c7c2bdd1f2e922bd01d3a69b15c3a0fdcd8548f6/numpy-2.3.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata
  Downloading numpy-2.3.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 1.7 MB/s eta 0:00:00
Collecting scipy
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/af/2c/40108915fd340c830aee332bb85a9160f99e90893e58008b659b9f3dddc0/scipy-1.16.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
  Downloading scipy-1.16.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 4.0 MB/s eta 0:00:00
Downloading numpy-2.3.1-cp311-cp311-manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 60.2 MB/s eta 0:00:00:00:0100:01
Downloading scipy-1.16.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 37.0 MB/s eta 0:00:00:00:0100:01
Installing collected packages: numpy, scipy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.3.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.1 which is incompatible.
sklearn-compat 0.1.3 requires scikit-learn<1.7,>=1.2, but you have scikit-learn 1.7.0 which is incompatible.
lightning 2.2.0.post0 requires fsspec[http]<2025.0,>=2022.5.0, but you have fsspec 2025.5.1 which is incompatible.
lightning 2.2.0.post0 requires packaging<25.0,>=20.0, but you have packaging 25.0 which is incompatible.
py-irt 0.6.2 requires torch==2, but you have torch 2.5.1 which is incompatible.
Successfully installed numpy-2.3.0 scipy-1.16.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install -e ..

Obtaining file:///home/sagar/winogender_contextuality
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: winogender_contextuality
  Building editable for winogender_contextuality (pyproject.toml) ... done
  Created wheel for winogender_contextuality: filename=winogender_contextuality-0.0.1-py3-none-any.whl size=3560 sha256=bbf675f1ff1d7b7cd027bac5bb1eedb1e30e6a1f581cfd88de8f31cec5f7e462
  Stored in directory: /tmp/pip-ephem-wheel-cache-d9wg_9ku/wheels/49/60/47/f23891bb1a09f2022418df9bc5d11c1d70a33f8f18763de816
Successfully built winogender_contextuality
Installing collected packages: winogender_contextuality
  Attempting uninstall: winogender_contextuality
    Found existing installation: winogender_contextuality 0.0.1
    Uninstalling winogender_contextuality-0.0.1:
      Successfully uninstalled winogender_contextuality-0.0.1
Successfully installed winogender_contextuality-0.0.1
Note: you may need to restart the kernel to use updated packages.

import winogender_contextuality

In [1]:
from winogender_contextuality.modeling.contextuality import *

2025-07-21 19:46:11.326 | INFO     | winogender_contextuality.config:<module>:13 - PROJ_ROOT path is: /home/sagar/winogender_contextuality
2025-07-21 19:46:11.327 | INFO     | winogender_contextuality.config:<module>:17 - DATA_ROOT path is: /data_users1/sagar/winogender_contextuality
2025-07-21 19:46:17.631112: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1753141577.649914 1143536 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1753141577.655736 1143536 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1753141577.668950 1143536 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1753141577.668982 1143536 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1753141577.668984 1143536 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1753141577.668986 1143536 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-07-21 19:46:17.673300: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

2025-07-21 19:46:20.292 | INFO     | winogender_contextuality.modeling.run_local:<module>:12 - torch available: False
2025-07-21 19:46:20.293 | INFO     | winogender_contextuality.modeling.run_local:<module>:13 - None

In [2]:
observations = ['a', 'b']
measurements = ['reg', 'prime']
outcomes = [0,1]

test = MeasurementScenario(
    observations = observations,
    measurements = measurements,
    outcomes = outcomes
)

In [3]:
test.scenario

<xarray.DataArray (context_pair: 4, outcome_pair: 4)> Size: 128B
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
Coordinates:
  * context_pair  (context_pair) int64 32B 0 1 2 3
  * outcome_pair  (outcome_pair) int64 32B 0 1 2 3

In [4]:
sentence_pairs = []
for sentence in observations:
    pairs = []
    for measurement in measurements:
        print((sentence, measurement))
        pairs.append(test.context_idx.get((sentence, measurement)))
    sentence_pairs.append(pairs)

('a', 'reg')
('a', 'prime')
('b', 'reg')
('b', 'prime')

In [5]:
sentence_pairs

[[0, 1], [2, 3]]

In [6]:
test.context_pairs

[(0, 2), (0, 3), (1, 2), (1, 3)]

In [7]:
test.incidence_matrix()

<xarray.DataArray (s: 16, t: 16)> Size: 2kB
array([[1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.]])
Coordinates:
  * s        (s) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
  * t        (t) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

In [8]:
probability_table = np.array([
    [1/2, 0,   0,   1/2],  # row 0: context (a, b)
    [3/8, 1/8, 1/8, 3/8],  # row 1: context (a', b)
    [3/8, 1/8, 1/8, 3/8],  # row 2: context (a, b')
    [1/8, 3/8, 3/8, 1/8]   # row 3: context (a', b')
])

In [9]:
test.scenario.values = probability_table

In [10]:
check_feasibility(test)

False

In [14]:
true_table = np.array([
    [1/4]*4,  # row 0: context (a, b)
    [1/4]*4,  # row 1: context (a', b)
    [1/4]*4,  # row 2: context (a, b')
    [1/4]*4   # row 3: context (a', b')
])

In [15]:
test.scenario.values = true_table

In [16]:
check_feasibility(test)

0

# Bug Fixing

In [10]:
# Dimensions from Abramsky and Brandenburger (2011)
num_rows = int((len(test.measurements) * len(test.outcomes)) ** len(test.observations))
num_columns = int(len(test.outcomes) ** (len(test.measurements) * len(test.observations)))

In [11]:
# All possible global assignments e.g. (a, a', b, b') [order comes from product function in self.contexts]
global_assignments = list(product([0, 1], repeat=len(test.observations)*len(test.measurements)))
global_assignments_map = {t: bstr for t,bstr in enumerate(global_assignments)}

# All pairs of context pairs and outcome pairs
context_outcome_pairs = product(test.context_pairs, test.outcome_pairs)
context_outcome_pairs_map = {p: pair for p, pair in enumerate(context_outcome_pairs)}

arr = xr.DataArray(np.zeros(shape=(num_rows, num_columns)),
                   dims=['s', 't'],
                   coords=[list(context_outcome_pairs_map.keys()), list(global_assignments_map.keys())]
                   )

In [12]:
arr

<xarray.DataArray (s: 16, t: 16)> Size: 2kB
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Coordinates:
  * s        (s) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
  * t        (t) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

In [14]:
arr.s

<xarray.DataArray 's' (s: 16)> Size: 128B
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
Coordinates:
  * s        (s) int64 128B 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15

In [15]:
test.context_pair_map

{0: (0, 2), 1: (0, 3), 2: (1, 2), 3: (1, 3)}

In [16]:
for p in arr.s:
    context_pair_idx, outcome_pair_idx = context_outcome_pairs_map[p.item()]
    print(context_pair_idx, outcome_pair_idx)

(0, 2) (0, 0)
(0, 2) (0, 1)
(0, 2) (1, 0)
(0, 2) (1, 1)
(0, 3) (0, 0)
(0, 3) (0, 1)
(0, 3) (1, 0)
(0, 3) (1, 1)
(1, 2) (0, 0)
(1, 2) (0, 1)
(1, 2) (1, 0)
(1, 2) (1, 1)
(1, 3) (0, 0)
(1, 3) (0, 1)
(1, 3) (1, 0)
(1, 3) (1, 1)

# DATA TEST

In [11]:
import pandas as pd
from tqdm.notebook import tqdm
import re

In [5]:
df = pd.read_csv('/data_users1/sagar/winogender_contextuality/data/processed/wino_pairs.tsv', sep='\t')

In [6]:
df.head()

,template_1,differences_1,referent_1,template_2,differences_2,referent_2
0,The technician told the customer that BLANK co...,"['he', 'she']",customer,The technician told the customer that BLANK ha...,"['he', 'she']",technician
1,The technician told the customer that BLANK co...,"['he', 'she']",customer,The technician told the customer that BLANK ha...,"['he', 'she']",technician
2,The technician told the customer that BLANK co...,"['he', 'she']",customer,The technician told the customer that BLANK ha...,"['he', 'she']",technician
3,The technician told the customer that BLANK co...,"['he', 'she']",customer,The technician told the customer that BLANK ha...,"['he', 'she']",technician
4,The technician told the customer that BLANK co...,"['he', 'she']",customer,The technician told the customer that BLANK ha...,"['he', 'she']",technician

In [27]:
input_path = '/data_users1/sagar/winogender_contextuality/data/raw/templates.tsv'

df = pd.read_csv(input_path, sep="\t")

pronouns_dict = {
    '$POSS_PRONOUN': ['his', 'her'],
    '$NOM_PRONOUN': ['he', 'she'],
    '$ACC_PRONOUN': ['him', 'her']
}

new_rows = []
pbar = tqdm(range(0, len(df), 2))

for i in pbar:
    chunk = df[i:i+2].reset_index(drop=True)
    new_row = {}

    for idx in chunk.index:
        s = chunk.sentence[idx]
        s = s.replace('$OCCUPATION', f"{df['occupation(0)'][idx]}")
        s = s.replace('$PARTICIPANT', f"{df['other-participant(1)'][idx]}")
        match = re.search(r'\$[a-zA-Z_]\w*', s)
        if match:
            pronoun_type = match.group(0)
            s = s.replace(pronoun_type, 'BLANK')
            new_row[f"template_{idx+1}"] = s
            new_row[f"differences_{idx+1}"] = pronouns_dict[pronoun_type]
        else:
            logger.warning(f"Could not find a pronoun in {s}")

        if df.answer[idx]:
            new_row[f"referent_{idx+1}"] = df['other-participant(1)'][idx]
        else:
            new_row[f"referent_{idx+1}"] = df['occupation(0)'][idx]

    new_rows.append(new_row)

# Adding a test row
test_row = new_rows[-1].copy()
test_row['differences_1'] = ['she', 'orangutan']
test_row['differences_2'] = ['she', 'orangutan']
new_rows.append(test_row)

    

output_df = pd.DataFrame(new_rows)
output_df

  0%|          | 0/60 [00:00<?, ?it/s]

,template_1,differences_1,referent_1,template_2,differences_2,referent_2
0,The technician told the customer that BLANK co...,"[he, she]",customer,The technician told the customer that BLANK ha...,"[he, she]",technician
1,The customer met with the technician to get he...,"[his, her]",customer,The customer met with the technician to find o...,"[he, she]",technician
2,The technician gave the customer feedback on B...,"[his, her]",customer,The customer gave the technician feedback on B...,"[his, her]",technician
3,The technician informed the customer that BLAN...,"[he, she]",customer,The technician informed the customer that BLAN...,"[he, she]",technician
4,The technician told the customer that BLANK sh...,"[he, she]",customer,The technician told the customer that BLANK wa...,"[he, she]",technician
...,...,...,...,...,...,...
56,The technician came out to apologize to the cu...,"[his, her]",customer,The technician came out to apologize to the cu...,"[his, her]",technician
57,The technician told the customer that BLANK wo...,"[he, she]",customer,The technician told the customer that BLANK wo...,"[he, she]",technician
58,The technician had to rescue the customer from...,"[he, she]",customer,The technician had to rescue the customer from...,"[he, she]",technician
59,The technician asked the customer to sign in s...,"[he, she]",customer,The technician asked the customer to sign in s...,"[he, she]",technician
60,The technician asked the customer to sign in s...,"[she, orangutan]",customer,The technician asked the customer to sign in s...,"[she, orangutan]",technician

In [23]:
test_row = new_rows[-1]
test_row['differences_1'] = ['she', 'orangutan']
test_row['differences_2'] = ['she', 'orangutan']
test_row

{'template_1': 'The technician asked the customer to sign in so that BLANK could update the guest log.',
 'differences_1': ['she', 'orangutan'],
 'referent_1': 'customer',
 'template_2': 'The technician asked the customer to sign in so that BLANK could be issued a guest badge.',
 'differences_2': ['she', 'orangutan'],
 'referent_2': 'technician'}